openapi: 3.0.0
info:
  title: ""
  version: 1.0.0
servers:
- url: /
paths:
  /v1/rule-group-sets:
    get:
      description: No description available
      externalDocs:
        url: ""
      operationId: RuleGroupSets_List
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RuleGroupSetListing"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: List Recording Rules
      tags:
      - Recording Rules Service
    post:
      description: No description available
      externalDocs:
        url: ""
      operationId: RuleGroupSets_Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Create_Rule_Group_Set"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateRuleGroupSetResult"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Create Recording Rules
      tags:
      - Recording Rules Service
  /v1/rule-group-sets/{id}:
    delete:
      description: No description available
      externalDocs:
        url: ""
      operationId: RuleGroupSets_Delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Delete Recording Rules
      tags:
      - Recording Rules Service
    get:
      description: No description available
      externalDocs:
        url: ""
      operationId: RuleGroupSets_Fetch
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutRuleGroupSet"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Get Recording Rules
      tags:
      - Recording Rules Service
    put:
      description: No description available
      externalDocs:
        url: ""
      operationId: RuleGroupSets_Update
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Update_Rule_Group_Set"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Update Recording Rules
      tags:
      - Recording Rules Service
components:
  schemas:
    ColorsByAggregation:
      additionalProperties: false
      properties:
        aggregation:
          $ref: "#/components/schemas/ColorsByAggregation"
      type: object
    ColorsByGroupBy:
      additionalProperties: false
      properties:
        groupBy:
          $ref: "#/components/schemas/ColorsByGroupBy"
      type: object
    ColorsByStack:
      additionalProperties: false
      properties:
        stack:
          $ref: "#/components/schemas/ColorsByStack"
      type: object
    CreateRuleGroupSetResult:
      description: Result of creating a rule group set.
      example:
        id: id
      externalDocs:
        description: Find out more about recording rules
        url: https://coralogix.com/docs/user-guides/data-transformation/metric-rules/recording-rules/
      properties:
        id:
          type: string
      title: Create Rule Group Set Result
      type: object
    FieldGroup:
      properties:
        name:
          type: string
        value:
          type: string
      type: object
    FilterPathAndValues:
      oneOf:
      - $ref: "#/components/schemas/FilterPathAndValuesMultipleValues"
      - $ref: "#/components/schemas/FilterPathAndValuesFilters"
    FilterPathAndValuesFilters:
      additionalProperties: false
      description: This data structure represents a filter path and values
      externalDocs:
        url: ""
      properties:
        filters:
          $ref: "#/components/schemas/Filters"
        path:
          example: test
          type: string
      required:
      - path
      - values
      title: FilterPathAndValues
      type: object
    FilterPathAndValuesMultipleValues:
      additionalProperties: false
      description: This data structure represents a filter path and values
      externalDocs:
        url: ""
      properties:
        multipleValues:
          $ref: "#/components/schemas/MultipleValues"
        path:
          example: test
          type: string
      required:
      - path
      - values
      title: FilterPathAndValues
      type: object
    Filters:
      description: This data structure represents a filter
      externalDocs:
        url: ""
      properties:
        operator:
          $ref: "#/components/schemas/v3.FilterOperator"
        pathAndValues:
          items:
            $ref: "#/components/schemas/FilterPathAndValues"
          type: array
      required:
      - pathAndValues
      title: Filters
      type: object
    InRule:
      description: A rule within a group that defines a recording rule expression.
      externalDocs:
        description: Find out more about recording rules
        url: https://coralogix.com/docs/user-guides/data-transformation/metric-rules/recording-rules/
      properties:
        expr:
          type: string
        labels:
          additionalProperties:
            type: string
          type: object
        record:
          type: string
      title: In Rule
      type: object
    InRuleGroup:
      description: A group of recording rules.
      externalDocs:
        description: Find out more about recording rules
        url: https://coralogix.com/docs/user-guides/data-transformation/metric-rules/recording-rules/
      properties:
        id:
          type: string
        interval:
          format: int64
          type: integer
        limit:
          example: ""
          format: int64
          type: string
        name:
          type: string
        rules:
          items:
            $ref: "#/components/schemas/InRule"
          type: array
        version:
          format: int64
          type: integer
      title: In Rule Group
      type: object
    MultipleValues:
      properties:
        matcher:
          $ref: "#/components/schemas/events.v3.FilterMatcher"
        values:
          items:
            type: string
          type: array
      type: object
    OutRule:
      example:
        lastEvalDurationMs: ""
        record: record
        expr: expr
        labels:
          key: labels
      properties:
        expr:
          type: string
        labels:
          additionalProperties:
            type: string
          type: object
        lastEvalDurationMs:
          example: ""
          format: int64
          type: string
        record:
          type: string
      type: object
    OutRuleGroup:
      example:
        limit: ""
        name: name
        interval: 0
        rules:
        - lastEvalDurationMs: ""
          record: record
          expr: expr
          labels:
            key: labels
        - lastEvalDurationMs: ""
          record: record
          expr: expr
          labels:
            key: labels
        id: id
        lastEvalAt: ""
        version: 6
      properties:
        id:
          type: string
        interval:
          format: int64
          type: integer
        lastEvalAt:
          example: ""
          format: int64
          type: string
        limit:
          example: ""
          format: int64
          type: string
        name:
          type: string
        rules:
          items:
            $ref: "#/components/schemas/OutRule"
          type: array
        version:
          format: int64
          type: integer
      type: object
    OutRuleGroupSet:
      description: An output set of rule groups.
      example:
        name: name
        groups:
        - limit: ""
          name: name
          interval: 0
          rules:
          - lastEvalDurationMs: ""
            record: record
            expr: expr
            labels:
              key: labels
          - lastEvalDurationMs: ""
            record: record
            expr: expr
            labels:
              key: labels
          id: id
          lastEvalAt: ""
          version: 6
        - limit: ""
          name: name
          interval: 0
          rules:
          - lastEvalDurationMs: ""
            record: record
            expr: expr
            labels:
              key: labels
          - lastEvalDurationMs: ""
            record: record
            expr: expr
            labels:
              key: labels
          id: id
          lastEvalAt: ""
          version: 6
        id: id
      externalDocs:
        description: Find out more about recording rules
        url: https://coralogix.com/docs/user-guides/data-transformation/metric-rules/recording-rules/
      properties:
        groups:
          items:
            $ref: "#/components/schemas/OutRuleGroup"
          type: array
        id:
          type: string
        name:
          type: string
      title: Out Rule Group Set
      type: object
    RuleGroupSetListing:
      description: A listing of rule group sets.
      example:
        sets:
        - name: name
          groups:
          - limit: ""
            name: name
            interval: 0
            rules:
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            id: id
            lastEvalAt: ""
            version: 6
          - limit: ""
            name: name
            interval: 0
            rules:
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            id: id
            lastEvalAt: ""
            version: 6
          id: id
        - name: name
          groups:
          - limit: ""
            name: name
            interval: 0
            rules:
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            id: id
            lastEvalAt: ""
            version: 6
          - limit: ""
            name: name
            interval: 0
            rules:
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            - lastEvalDurationMs: ""
              record: record
              expr: expr
              labels:
                key: labels
            id: id
            lastEvalAt: ""
            version: 6
          id: id
      externalDocs:
        description: Find out more about recording rules
        url: https://coralogix.com/docs/user-guides/data-transformation/metric-rules/recording-rules/
      properties:
        sets:
          items:
            $ref: "#/components/schemas/OutRuleGroupSet"
          type: array
      title: Rule Group Set Listing
      type: object
    common.Group:
      properties:
        field:
          $ref: "#/components/schemas/FieldGroup"
        groups:
          items:
            $ref: "#/components/schemas/common.Group"
          type: array
        value:
          format: double
          type: number
      type: object
    events.v3.FilterMatcher:
      enum:
      - FILTER_MATCHER_TEXT_OR_UNSPECIFIED
      - FILTER_MATCHER_REGEXP
      type: string
    v3.FilterOperator:
      enum:
      - FILTER_OPERATOR_AND_OR_UNSPECIFIED
      - FILTER_OPERATOR_OR
      type: string
    Create_Rule_Group_Set:
      additionalProperties: false
      description: A set of rule groups to create.
      properties:
        groups:
          items:
            $ref: "#/components/schemas/InRuleGroup"
          type: array
        name:
          type: string
      title: Create Rule Group Set
      type: object
    Update_Rule_Group_Set:
      additionalProperties: false
      description: A set of rule groups to update.
      properties:
        groups:
          items:
            $ref: "#/components/schemas/InRuleGroup"
          type: array
        name:
          type: string
      title: Update Rule Group Set
      type: object
  securitySchemes:
    apiKeyAuth:
      description: API key authentication
      in: header
      name: Authorization
      type: apiKey
